### ISSUE TITLE
Add test assertion to make sure we don't install multiverse packages

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/jammy-base-stack#30]
In #29 we re-added the `multiverse` package source to the stack images with the intention of enabling use cases that might need packages from this location.

We do not want to ship any packages from `multiverse` in the stacks themselves, as explained in the linked PR. To prevent against this in the future, we should add a test assertion to the suite that checks that no packages come from the `multiverse` repository.

**Comment by robdimsdale** [comment]
This was fixed in #45 . Closing.
